### ISSUE TITLE
Regarding to run the code for customized data

### ISSUE THREAD

**Issue by gauraviiita** [zdwww/EgoGaussian#2]
Hi 
Nice work!!

Could you tell me the approximate date when will you release the Tutorial for running EgoGaussian on customized data?

**Comment by zdwww** [comment]
Thank you for your interest in our project. As I am currently in the middle of my PhD applications, I may not be able to commit to this before mid-January. But here's a brief overview of what I did 
(1) Run EgoHOS https://github.com/owenzlz/EgoHOS to identify hand segmentation 
(2) Run a similar pipeline as EPIC Fields https://github.com/epic-kitchens/epic-fields-code to obtain camera poses, though it's better to exclude hand segmentation obtained in previous step
(3) Select the object several frames right before the interaction and run track anything https://github.com/gaomingqi/Track-Anything to segment the interacted objects

**Comment by gauraviiita** [comment]
Thank you for getting back to me. I will apply these steps and best wishes for your PhD applications.

**Comment by gauraviiita** [comment]
Hello @zdwww , I hope your application process is going well.

I have a question about the id.txt file. What does its content mean, "ZY20210800001/H1/C8/N36/S319/s02/T2"?

And for custom data, do I have to write another data_type, or do I have to place my data, whether EK or HOI?

Also, I hope you will upload the original custom data pipeline soon.
